name: mayung_media
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.11

flutter_native_splash:
  color: "#1E293B"
  image: assets/images/logo_putih.webp
  
  android_12:
    image: assets/images/logo_putih.webp
    color: "#1E293B"
    icon_backgroundColor: "#1E293B"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_putih.webp
    - assets/images/IMG_1344.JPG
    - assets/images/author.webp
    - assets/images/Alam.webp
    - assets/images/Budaya.webp
    - assets/images/Budaya 2.webp
    - assets/images/Suara.webp
    - assets/images/SUARA 2.webp
    - assets/images/Berdaya.webp

  fonts:
    - family: judul
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf 
        - asset: fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic
    - family: primary
      fonts:
        - asset: fonts/Outfit-VariableFont_wght.ttf